### ISSUE TITLE
hello , how i can make this script responsive ?

### ISSUE THREAD

**Issue by mrssam** [seancoyne/pano#1]
hi, you have nice script it's good but i need to add something to make it responsive please tell me how ,it must show the current view of panoramic image as full size of div or window 
when i make window size big than 500px it show me the image as tile images i want to make it as fill image of window 
Best Regards

**Comment by seancoyne** [comment]
Use CSS to set the background image to no-repeat and set it to % dimensions.

**Comment by seancoyne** [comment]
The demo is responsive http://blog.n42designs.com/pano/

**Comment by seancoyne** [comment]
I think I see what you're saying.  Yeah, you can't make it larger than the actual size of the image.  It doesn't scale the image up.  It needs to repeat-x in order for the viewer to move the image into view.  So if you need it larger you'll need a larger/higher res version of the image.
