### ISSUE TITLE
Automatic running

### ISSUE THREAD

**Issue by full-blood** [seancoyne/pano#4]
Is it possible to have an automatic running on loading?
If I just write "pano.moveRight();" it doesn't work.

**Comment by seancoyne** [comment]
You need to run it during the onLoad event.  Something like jQuery's `document.ready` or just using a basic JS event handler

**Comment by full-blood** [comment]
Thank you for your answer. It doesn't work, but I let this idea because this do too much problems.
Also thanks for this great code !

Have a nice day,
Antoine
