### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by LaurenceRLewis** [seancoyne/pano#5]
I cannot get the image moving using the left/right arrow keys. I tried updating the script to include a click event as well as mousedown but this breaks the functionality.

Could you explain how or if the pano effect works for keyboard only users.

Thanks.

**Comment by seancoyne** [comment]
Just use simple jquery event listeners to listen for keydown, keyup events and call the appropriate moveLeft/Right and stopMoving functions.
